import fs from 'fs';
import path from 'path';

/**
 * Generate .localhaus/Dockerfile and .localhaus/docker-compose.yml for a project.
 * Will NOT overwrite existing files unless force=true.
 *
 * @param {string} projectPath - Absolute path to the project
 * @param {object} detection - Result from ProjectDetector.detectProjectType()
 * @param {number} assignedPort - Host port to expose
 * @param {{ force?: boolean }} [opts]
 * @returns {{ composePath: string, dockerfilePath: string, skipped?: boolean }}
 */
export function generateCompose(projectPath, detection, assignedPort, opts = {}) {
  const localhausDir = path.join(projectPath, '.localhaus');
  const composePath = path.join(localhausDir, 'docker-compose.yml');
  const dockerfilePath = path.join(localhausDir, 'Dockerfile');

  // Don't overwrite existing files unless forced
  if (!opts.force && fs.existsSync(composePath) && fs.existsSync(dockerfilePath)) {
    return { composePath, dockerfilePath, skipped: true };
  }

  fs.mkdirSync(localhausDir, { recursive: true });

  const dockerfile = generateDockerfile(detection);
  const compose = generateComposeYaml(detection, assignedPort);

  if (!fs.existsSync(dockerfilePath) || opts.force) {
    fs.writeFileSync(dockerfilePath, dockerfile);
  }
  if (!fs.existsSync(composePath) || opts.force) {
    fs.writeFileSync(composePath, compose);
  }

  return { composePath, dockerfilePath, skipped: false };
}

function generateDockerfile(detection) {
  if (detection.type === 'node') {
    return generateNodeDockerfile(detection);
  }
  if (detection.type === 'python') {
    return generatePythonDockerfile(detection);
  }
  if (detection.type === 'go') {
    return generateGoDockerfile();
  }
  throw new Error(`Unsupported project type for Dockerfile generation: ${detection.type}`);
}

function generateNodeDockerfile(detection) {
  const pm = detection.packageManager || { name: 'npm', install: 'npm install' };
  const installCmd = detection.installCommand || pm.install;

  // Copy lock files alongside package.json
  const copyFiles = ['package.json'];
  if (pm.lockFile) copyFiles.push(pm.lockFile);
  const copyLine = `COPY ${copyFiles.join(' ')} ./`;

  // For bun, use oven/bun image
  const baseImage = pm.name === 'bun' ? 'oven/bun:latest' : 'node:20-slim';

  // For pnpm, need to enable corepack
  const pnpmSetup = pm.name === 'pnpm' ? '\nRUN corepack enable' : '';

  return `# Auto-generated by localhaus — do not edit
FROM ${baseImage}
WORKDIR /app${pnpmSetup}
${copyLine}
RUN ${installCmd}
COPY . .
CMD ${formatCmd(detection.devCommand)}
`;
}

function generatePythonDockerfile(detection) {
  const installCmd = detection.installCommand || 'pip install -r requirements.txt';
  const copyLine = installCmd.includes('pyproject')
    ? 'COPY pyproject.toml ./\nCOPY setup.py* setup.cfg* ./'
    : 'COPY requirements.txt ./';

  return `# Auto-generated by localhaus — do not edit
FROM python:3.12-slim
WORKDIR /app
${copyLine}
RUN ${installCmd}
COPY . .
CMD ${formatCmd(detection.devCommand)}
`;
}

/**
 * Format a dev command as a Dockerfile CMD.
 * Uses exec form ["a","b"] for simple commands, shell form for commands
 * with shell metacharacters (pipes, redirects, &&, etc.)
 */
function formatCmd(devCommand) {
  if (/[|&;<>`$"'\\]/.test(devCommand)) {
    // Shell metacharacters present — use shell form so sh interprets them
    return `["sh", "-c", ${JSON.stringify(devCommand)}]`;
  }
  return JSON.stringify(devCommand.split(' '));
}

function generateGoDockerfile() {
  return `# Auto-generated by localhaus — do not edit
FROM golang:1.22-alpine
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
CMD ["go", "run", "."]
`;
}

function generateComposeYaml(detection, assignedPort) {
  const internalPort = detection.port;
  const volumes = ['      - .:/app'];

  // For Node, add anonymous volume for node_modules
  if (detection.type === 'node') {
    volumes.push('      - /app/node_modules');
  }

  const envVars = [];
  if (detection.type === 'node') {
    envVars.push('      - NODE_ENV=development');
  }
  if (detection.type === 'python') {
    envVars.push('      - PYTHONDONTWRITEBYTECODE=1');
    envVars.push('      - PYTHONUNBUFFERED=1');
  }

  const envSection = envVars.length
    ? `\n    environment:\n${envVars.join('\n')}`
    : '';

  return `# Auto-generated by localhaus — do not edit
services:
  app:
    build:
      context: ..
      dockerfile: .localhaus/Dockerfile
    ports:
      - "${assignedPort}:${internalPort}"
    volumes:
${volumes.join('\n')}${envSection}
    command: ${detection.devCommand}
`;
}

export default { generateCompose };
