import fs from 'fs';
import path from 'path';

/**
 * Generate .jump.sh/Dockerfile and .jump.sh/docker-compose.yml for a project.
 * Will NOT overwrite existing files unless force=true.
 *
 * @param {string} projectPath - Absolute path to the project
 * @param {object} detection - Result from ProjectDetector.detectProjectType()
 * @param {number} assignedPort - Host port to expose
 * @param {{ force?: boolean }} [opts]
 * @returns {{ composePath: string, dockerfilePath: string, skipped?: boolean }}
 */
export function generateCompose(projectPath, detection, assignedPort, opts = {}) {
  const jumpshDir = path.join(projectPath, '.jump.sh');
  const composePath = path.join(jumpshDir, 'docker-compose.yml');
  const dockerfilePath = path.join(jumpshDir, 'Dockerfile');
  const transformedEnvPath = path.join(jumpshDir, '.env.docker');

  // Don't overwrite existing files unless forced
  if (!opts.force && fs.existsSync(composePath) && fs.existsSync(dockerfilePath)) {
    return { composePath, dockerfilePath, skipped: true };
  }

  fs.mkdirSync(jumpshDir, { recursive: true });


  // Generate transformed env file for Docker runtime:
  // rewrite localhost/127.0.0.1 to host.docker.internal so services on host are reachable.
  const projectEnvPath = path.join(projectPath, '.env');
  if (fs.existsSync(projectEnvPath)) {
    try {
      const raw = fs.readFileSync(projectEnvPath, 'utf8');
      const transformed = raw
        .split('\n')
        .map((line) => {
          const t = line.trim();
          if (!t || t.startsWith('#') || !line.includes('=')) return line;
          const i = line.indexOf('=');
          const key = line.slice(0, i);
          const value = line.slice(i + 1)
            .replace(/localhost/g, 'host.docker.internal')
            .replace(/127\.0\.0\.1/g, 'host.docker.internal');
          return `${key}=${value}`;
        })
        .join('\n');
      fs.writeFileSync(transformedEnvPath, transformed + (transformed.endsWith('\n') ? '' : '\n'));
    } catch { /* best effort */ }
  }

  // Write .dockerignore in project root to exclude large/irrelevant directories
  const dockerignorePath = path.join(projectPath, '.dockerignore');
  if (!fs.existsSync(dockerignorePath)) {
    const dockerignore = [
      'node_modules',
      '.git',
      '.jump.sh',
      'dump',
      'data',
      'tmp',
      '.worktrees',
      '*.log',
      '.env*',
      'coverage',
      '.nyc_output',
      'dist',
      'build',
      '.DS_Store',
    ].join('\n');
    fs.writeFileSync(dockerignorePath, dockerignore + '\n');
  }

  const dockerfile = generateDockerfile(detection);
  const compose = generateComposeYaml(detection, assignedPort);

  if (!fs.existsSync(dockerfilePath) || opts.force) {
    fs.writeFileSync(dockerfilePath, dockerfile);
  }
  if (!fs.existsSync(composePath) || opts.force) {
    fs.writeFileSync(composePath, compose);
  }

  return { composePath, dockerfilePath, skipped: false };
}

function generateDockerfile(detection) {
  if (detection.type === 'node') {
    return generateNodeDockerfile(detection);
  }
  if (detection.type === 'python') {
    return generatePythonDockerfile(detection);
  }
  if (detection.type === 'go') {
    return generateGoDockerfile();
  }
  throw new Error(`Unsupported project type for Dockerfile generation: ${detection.type}`);
}

function generateNodeDockerfile(detection) {
  const pm = detection.packageManager || { name: 'npm', install: 'npm install' };
  const installCmd = detection.installCommand || pm.install;

  // Copy lock files alongside package.json
  const copyFiles = ['package.json'];
  if (pm.lockFile) copyFiles.push(pm.lockFile);
  const copyLine = `COPY ${copyFiles.join(' ')} ./`;

  // For bun, use oven/bun image
  const baseImage = pm.name === 'bun' ? 'oven/bun:latest' : 'node:20-slim';

  // For pnpm, need to enable corepack
  const pnpmSetup = pm.name === 'pnpm' ? '\nRUN corepack enable' : '';

  // Build tools for native modules (node-gyp needs python3, make, g++)
  // oven/bun is Debian-based too, so apt-get works for both
  const buildTools = pm.name === 'bun'
    ? ''
    : '\nRUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*';

  return `# Auto-generated by jump.sh — do not edit
FROM ${baseImage}${buildTools}
WORKDIR /app${pnpmSetup}
${copyLine}
RUN ${installCmd}
COPY . .
CMD ${formatCmd(detection.devCommand)}
`;
}

function generatePythonDockerfile(detection) {
  const installCmd = detection.installCommand || 'pip install -r requirements.txt';
  const copyLine = installCmd.includes('pyproject')
    ? 'COPY pyproject.toml ./\nCOPY setup.py* setup.cfg* ./'
    : 'COPY requirements.txt ./';

  return `# Auto-generated by jump.sh — do not edit
FROM python:3.12-slim
WORKDIR /app
${copyLine}
RUN ${installCmd}
COPY . .
CMD ${formatCmd(detection.devCommand)}
`;
}

/**
 * Format a dev command as a Dockerfile CMD.
 * Uses exec form ["a","b"] for simple commands, shell form for commands
 * with shell metacharacters (pipes, redirects, &&, etc.)
 */
function formatCmd(devCommand) {
  if (/[|&;<>`$"'\\]/.test(devCommand)) {
    // Shell metacharacters present — use shell form so sh interprets them
    return `["sh", "-c", ${JSON.stringify(devCommand)}]`;
  }
  return JSON.stringify(devCommand.split(' '));
}

function generateGoDockerfile() {
  return `# Auto-generated by jump.sh — do not edit
FROM golang:1.22-alpine
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
CMD ["go", "run", "."]
`;
}

function generateComposeYaml(detection, assignedPort) {
  const internalPort = detection.port;
  // Volume paths are relative to compose file in .jump.sh/, so .. = project root
  const volumes = ['      - ..:/app'];

  // For Node, add anonymous volume to prevent host node_modules overwrite
  if (detection.type === 'node') {
    volumes.push('      - /app/node_modules');
  }

  const envVars = [];
  if (detection.type === 'node') {
    envVars.push('      - NODE_ENV=development');
  }
  if (detection.type === 'python') {
    envVars.push('      - PYTHONDONTWRITEBYTECODE=1');
    envVars.push('      - PYTHONUNBUFFERED=1');
  }

  const envSection = envVars.length
    ? `\n    environment:\n${envVars.join('\n')}`
    : '';

  const envFileSection = `\n    env_file:\n      - ../.env\n      - ./.env.docker`;


  return `# Auto-generated by jump.sh — do not edit
services:
  app:
    build:
      context: ..
      dockerfile: .jump.sh/Dockerfile
    ports:
      - "${assignedPort}:${internalPort}"
    volumes:
${volumes.join('\n')}${envFileSection}${envSection}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    command: ${detection.devCommand}
`;
}

export default { generateCompose };
