import { parseArgs } from 'node:util';
import { execSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, '..', '..');
const JUMPSH_DIR = path.join(os.homedir(), '.jump.sh');

export default async function install(argv) {
  const { values } = parseArgs({
    args: argv,
    options: {
      uninstall: { type: 'boolean', default: false },
      help: { type: 'boolean', short: 'h', default: false },
    },
  });

  if (values.help) {
    console.log(`Usage: jumpsh install [--uninstall]

Install the jump.sh daemon service. If JUMPSH_HTTPS=true and certs
are missing, automatically downloads them from the jump.sh server.

Options:
  --uninstall   Remove daemon service and optionally clean state
  --help, -h    Show this help
`);
    process.exit(0);
  }

  if (values.uninstall) {
    await uninstall();
    return;
  }

  const platform = os.platform();
  if (platform !== 'darwin' && platform !== 'linux') {
    console.error(`Unsupported platform: ${platform}. Only macOS and Linux are supported.`);
    process.exit(1);
  }

  // Track created artifacts for rollback on failure
  const created = [];

  try {
    await doInstall(platform, created);
  } catch (err) {
    console.error(`\nInstall failed: ${err.message}`);
    // Rollback created artifacts
    if (created.length > 0) {
      console.log('Rolling back created artifacts...');
      for (const artifact of created.reverse()) {
        try {
          if (fs.existsSync(artifact)) {
            fs.unlinkSync(artifact);
            console.log(`  Removed: ${artifact}`);
          }
        } catch { /* best effort */ }
      }
    }
    process.exit(1);
  }

  console.log('\njump.sh installed successfully.');
  console.log('Run `jumpsh ls` to see your projects.');
}

async function doInstall(platform, created) {
  // Step 1: Create state directory
  fs.mkdirSync(JUMPSH_DIR, { recursive: true });
  fs.mkdirSync(path.join(JUMPSH_DIR, 'logs'), { recursive: true });
  console.log(`State directory: ${JUMPSH_DIR}`);

  // Step 2: Ensure certs if HTTPS is enabled
  const httpsEnabled = process.env.JUMPSH_HTTPS === 'true';
  if (httpsEnabled) {
    const { certsExist, downloadCerts } = await import('./certs.js');
    if (!certsExist()) {
      console.log('\nHTTPS is enabled but certs are missing. Attempting download...');
      try {
        await downloadCerts();
      } catch {
        console.log('\nCert download failed. You can fetch them later:');
        console.log('  jumpsh certs');
      }
    } else {
      console.log('TLS certificates: already present');
    }
  }

  // Step 3: Resolve the daemon exec command for the wrapper script
  const jumpshBin = isNpxRun() ? 'npx --yes jump.sh' : resolveGlobalBin();

  // Step 4: Write wrapper script
  const wrapperPath = path.join(JUMPSH_DIR, 'jumpsh-daemon.sh');
  const wrapperContent = `#!/usr/bin/env bash
# jump.sh daemon wrapper — resolves node via version managers
# Regenerated by 'jumpsh install'

# Try mise
for rc in "$HOME/.local/share/mise/activate.sh" \\
          "$HOME/.config/mise/activate.sh"; do
  if [ -f "$rc" ]; then
    eval "$(mise activate bash 2>/dev/null)" 2>/dev/null
    break
  fi
done

# Try fnm
if [ -d "$HOME/.fnm" ]; then
  eval "$("$HOME/.fnm/fnm" env 2>/dev/null)" 2>/dev/null
fi

# Try nvm
NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh" 2>/dev/null
fi

cd "${PACKAGE_ROOT}" 2>/dev/null
exec ${jumpshBin}
`;
  fs.writeFileSync(wrapperPath, wrapperContent, { mode: 0o755 });
  created.push(wrapperPath);
  console.log(`Wrapper script: ${wrapperPath}`);

  // Step 5: Write and enable service file
  if (platform === 'darwin') {
    await installMacOS(wrapperPath, created);
  } else {
    await installLinux(wrapperPath, created);
  }
}

async function installMacOS(wrapperPath, created) {
  const plistDir = path.join(os.homedir(), 'Library', 'LaunchAgents');
  fs.mkdirSync(plistDir, { recursive: true });
  const plistPath = path.join(plistDir, 'sh.jump.daemon.plist');

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>sh.jump.daemon</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${wrapperPath}</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${JUMPSH_DIR}/logs/daemon.log</string>
  <key>StandardErrorPath</key><string>${JUMPSH_DIR}/logs/daemon.err</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>JUMPSH_HTTPS</key><string>true</string>
    <key>HOME</key><string>${os.homedir()}</string>
  </dict>
</dict>
</plist>
`;

  fs.writeFileSync(plistPath, plist);
  created.push(plistPath);
  console.log(`LaunchAgent: ${plistPath}`);

  try {
    execSync(`launchctl bootstrap gui/$(id -u) "${plistPath}" 2>/dev/null || launchctl load -w "${plistPath}"`, {
      stdio: 'inherit',
    });
    console.log('Daemon started via launchd.');
  } catch {
    console.log('Note: Could not start daemon. You may need to load it manually or run `jumpsh` in foreground.');
  }
}

async function installLinux(wrapperPath, created) {
  const unitDir = path.join(os.homedir(), '.config', 'systemd', 'user');
  fs.mkdirSync(unitDir, { recursive: true });
  const unitPath = path.join(unitDir, 'jumpsh.service');

  const unit = `[Unit]
Description=jump.sh local dev daemon
After=network.target

[Service]
Type=simple
ExecStart=/bin/bash ${wrapperPath}
Restart=always
RestartSec=3
Environment=JUMPSH_HTTPS=true

[Install]
WantedBy=default.target
`;

  fs.writeFileSync(unitPath, unit);
  created.push(unitPath);
  console.log(`Systemd unit: ${unitPath}`);

  try {
    execSync('systemctl --user daemon-reload', { stdio: 'inherit' });
    execSync('systemctl --user enable --now jumpsh', { stdio: 'inherit' });
    console.log('Daemon started via systemd.');
  } catch {
    console.log('Note: Could not enable daemon via systemd. Run `jumpsh` in foreground instead.');
  }
}

function isNpxRun() {
  // npm sets npm_execpath when running via npx; also check for _npx cache paths
  const execPath = process.env.npm_execpath || '';
  if (execPath.includes('npx')) return true;
  if (PACKAGE_ROOT.includes('_npx') || PACKAGE_ROOT.includes('.npm/_npx')) return true;
  return false;
}

function resolveGlobalBin() {
  // Use the actual path to bin/jumpsh.js from our known package root.
  // Since we already blocked npx above, PACKAGE_ROOT is a stable location
  // (global install or a local project checkout).
  const binPath = path.join(PACKAGE_ROOT, 'bin', 'jumpsh.js');
  if (!fs.existsSync(binPath)) {
    throw new Error(`Cannot find jumpsh binary at ${binPath}`);
  }
  return `node "${binPath}"`;
}

async function uninstall() {
  const platform = os.platform();
  const removed = [];

  if (platform === 'darwin') {
    try {
      execSync('launchctl bootout gui/$(id -u)/sh.jump.daemon 2>/dev/null', { stdio: 'ignore' });
      removed.push('Stopped daemon');
    } catch { /* may not be running */ }

    const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'sh.jump.daemon.plist');
    if (fs.existsSync(plistPath)) {
      fs.unlinkSync(plistPath);
      removed.push(`Removed ${plistPath}`);
    }
  } else if (platform === 'linux') {
    try {
      execSync('systemctl --user stop jumpsh 2>/dev/null', { stdio: 'ignore' });
      execSync('systemctl --user disable jumpsh 2>/dev/null', { stdio: 'ignore' });
      removed.push('Stopped and disabled daemon');
    } catch { /* may not be running */ }

    const unitPath = path.join(os.homedir(), '.config', 'systemd', 'user', 'jumpsh.service');
    if (fs.existsSync(unitPath)) {
      fs.unlinkSync(unitPath);
      try { execSync('systemctl --user daemon-reload', { stdio: 'ignore' }); } catch {}
      removed.push(`Removed ${unitPath}`);
    }
  }

  const wrapperPath = path.join(JUMPSH_DIR, 'jumpsh-daemon.sh');
  if (fs.existsSync(wrapperPath)) {
    fs.unlinkSync(wrapperPath);
    removed.push(`Removed ${wrapperPath}`);
  }

  if (removed.length === 0) {
    console.log('Nothing to uninstall.');
  } else {
    for (const msg of removed) {
      console.log(`  ${msg}`);
    }
    console.log(`\nState directory kept: ${JUMPSH_DIR}`);
    console.log('To fully remove, run: rm -rf ~/.jump.sh');
  }
}
